openapi: 3.0.1
info:
  title: Task Microservice
  version: v1
paths:
  /task:
    put:
      summary: Creates a new task
      operationId: createTask
      security: 
      - JWT: [write]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: string
                necessaryPoints:
                  type:  integer
                taskTypeId:
                  type:  integer
                subject:
                  type:  integer
                module:
                  type:  integer
                lecture:
                  type:  integer
                difficulty:
                  type:  integer
      responses:
        '200':
          description: Ok
          
        '4XX':
          description: User Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error :
                    type: string
        
        '5XX':
          description: Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error :
                    type: string
        

    get:
      summary: Gets all tasks created by the user
      operationId: getTasks
      security:  
      - JWT: [read]
      responses:
        '200':
          description: Ok
        
        '4XX':
          description: User Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error :
                    type: string
        
        '5XX':
          description: Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error :
                    type: string

  /task/{taskId}:
    get:
      summary: Gets a task
      operationId: getTask
      security:  
      - JWT: [read]
      parameters:
        - name: taskId
          in: path
          required: true
          description: The unique task id
          schema:
            type: integer
            format: int64
            minimum: 0
      responses:
        '200':
          description: Ok
          
        '4XX':
          description: User Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error :
                    type: string
        
        '5XX':
          description: Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error :
                    type: string


  /task/search:
    get:
      summary: Gets all tasks based on parameters 
      operationId: searchTask
      security: 
      - JWT: [read]
      parameters: 
        - name: subject
          in : query
          required : true
          description: Subject
          schema :
            type: string
            format: string
            minimum: 0
        - name: module
          in : query
          required : true
          description: Module
          schema :
            type: string
            format: string
            minimum: 0
        - name: lecture
          in : query
          required : false
          description: Lecture
          schema :
            type: string
            format: string
            minimum: 0
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      type: object
                      properties:
                        task_id:
                          type: integer
                        task:
                          type: string
                        taskType:
                          type: string
                        necessaryPoints:
                          type: integer
                        subject:
                          type: string
                        lecture:
                          type: string
                        difficulty:
                          type: string
                        author:
                          type: string
                          
        '4XX':
          description: User Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error :
                    type: string
        
        '5XX':
          description: Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error :
                    type: string
                    


components:
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT